export const VIEW_ID = "gitSubmodule.repos";

export const GIT_SHOW_SCHEME = "gitsubmodule";

export const COMMANDS = {
  refresh: "gitSubmodule.refresh",
  openDiff: "gitSubmodule.openDiff",
  openChange: "gitSubmodule.openChange",
  openAllChanges: "gitSubmodule.openAllChanges",
  openFile: "gitSubmodule.openFile",
  openHEADFile: "gitSubmodule.openHEADFile",
  stage: "gitSubmodule.stage",
  stageAll: "gitSubmodule.stageAll",
  stageAllTracked: "gitSubmodule.stageAllTracked",
  stageAllUntracked: "gitSubmodule.stageAllUntracked",
  stageAllMerge: "gitSubmodule.stageAllMerge",
  unstage: "gitSubmodule.unstage",
  unstageAll: "gitSubmodule.unstageAll",
  clean: "gitSubmodule.clean",
  cleanAll: "gitSubmodule.cleanAll",
  cleanAllTracked: "gitSubmodule.cleanAllTracked",
  cleanAllUntracked: "gitSubmodule.cleanAllUntracked",
  commit: "gitSubmodule.commit",
  generateSubmoduleChore: "gitSubmodule.generateSubmoduleChore",
  checkoutBranch: "gitSubmodule.checkoutBranch",
  fetch: "gitSubmodule.fetch",
  pull: "gitSubmodule.pull",
  sync: "gitSubmodule.sync",
  publish: "gitSubmodule.publish",
  retryRestore: "gitSubmodule.retryRestore",
  fetchRemote: "gitSubmodule.fetchRemote",
} as const;

export const CONTEXT = {
  workspaceRoot: "gitSubmodule.workspaceRoot",
  submodule: "gitSubmodule.submodule",
  hasUpstream: "gitSubmodule.hasUpstream",
  noUpstream: "gitSubmodule.noUpstream",
  changeGroupMerge: "gitSubmodule.changeGroup.merge",
  changeGroupIndex: "gitSubmodule.changeGroup.index",
  changeGroupWorkingTree: "gitSubmodule.changeGroup.workingTree",
  changeGroupUntracked: "gitSubmodule.changeGroup.untracked",
  changeMerge: "gitSubmodule.change.merge",
  changeIndex: "gitSubmodule.change.index",
  changeWorkingTree: "gitSubmodule.change.workingTree",
  changeUntracked: "gitSubmodule.change.untracked",
  resourceFolderMerge: "gitSubmodule.resourceFolder.merge",
  resourceFolderIndex: "gitSubmodule.resourceFolder.index",
  resourceFolderWorkingTree: "gitSubmodule.resourceFolder.workingTree",
  resourceFolderUntracked: "gitSubmodule.resourceFolder.untracked",
  adoptedGroup: "gitSubmodule.adoptedGroup",
  adoptedPointer: "gitSubmodule.adoptedPointer",
  staged: "gitSubmodule.staged",
  unstaged: "gitSubmodule.unstaged",
  file: "gitSubmodule.file",
  message: "gitSubmodule.message",
} as const;
